name = "fastapi"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_TOKEN = "AbvDAAIncDExNmJjZDc0OThmZTU0NTNmOWEzNGEzZTJkYTFjZWJmMnAxNDgwNjc"
UPSTASH_REDIS_REST_URL = "https://peaceful-beagle-48067.upstash.io"
